#!/usr/bin/env bash
# Runs INSIDE the container, AFTER `repo init`, BEFORE `repo sync`.
#
# Writes .repo/local_manifests/warhol_removals.xml, removing projects a recovery
# build never touches — up front, so they are neither downloaded nor able to break
# Soong's whole-tree bootstrap (TWRP's manifest keeps projects whose Android.bp
# depends on modules defined in projects it removes; see BUILDING.md).
#
# THREE THINGS THAT BIT US, all encoded here:
#
#  1. Use the EFFECTIVE manifest (`repo manifest`), not the raw XML files.
#     .repo/manifests/ contains default.xml AND remove-minimal.xml; the latter
#     already removes many projects. Emitting <remove-project> for something
#     already removed is a hard error:
#        remove-project element specifies non-existent project: platform/packages/services/Car
#
#  2. Do NOT use `repo list`. repo refuses to list anything when any local
#     manifest is malformed, so a script using it cannot repair its own bad output.
#
#  3. Write atomically, and delete any existing file first — a half-written local
#     manifest bricks repo until removed by hand.
set -euo pipefail
cd /aosp
rm -f .repo/local_manifests/warhol_removals.xml
mkdir -p .repo/local_manifests

repo manifest -o /tmp/effective.xml 2>/dev/null

python3 - <<'PY'
import os, xml.etree.ElementTree as ET

# DO NOT ADD "cts" HERE.
# It was in this list once. `cts` defines cts_defaults, cts_support_defaults and
# mts-target-sdk-version-current, which are consumed by test targets scattered
# through frameworks/base, packages/modules/{Permission,HealthFitness,Profiling,
# IPsec,Connectivity}, system/timezone and tools/platform-compat. Removing cts
# turned 13 genuine bootstrap errors into 86 directory deletions — 73 of them
# caused by nothing but this line. Keeping cts costs ~2 GB and is worth it.
#
# The entries below are projects with no consumers outside themselves (or whose
# consumers are also listed), verified against a clean sync.
DROP = [
    "test/suite_harness", "tools/tradefederation", "tools/loganalysis",
    "packages/modules/AdServices",
    "hardware/google/aemu", "system/secretkeeper",
    # NOT system/chre: it provides android.chre.flags-aconfig, and removing it makes
    # Soong panic in aconfig codegen ("Exactly one aconfig_declarations property
    # required") rather than fail cleanly. Same lesson as cts — every project removed
    # is a chance to break something that is still present.
    "vendor/qcom/",
]

# Projects TWRP removes but that DEFINE modules other kept projects depend on.
# Adding the provider back is always correct; deleting the consumer is not — it
# can delete definitions in turn and cascade (that mistake turned 13 real errors
# into 86 deletions, twice). Only add what is actually needed, with the reason.
ADD_BACK = {
    # packages/services/Car was tried here and REVERTED. It does satisfy
    # cts/tests/tests/car and automotive's vhalclient_defaults, but Car itself then
    # needs car-frameworks-service-module and more — an unbounded chain, because
    # TWRP removes the whole car stack deliberately. Cheaper and bounded: drop the
    # automotive HAL and the one leaf CTS car test instead (see prune-subdirs.sh).
    "packages/modules/NetworkStack":    "platform/packages/modules/NetworkStack",
    #   defines libnetworkstackutilsjni_deps, needed by Connectivity/tests/common
}

root = ET.parse("/tmp/effective.xml").getroot()
projects = {}
for p in root.iter("project"):
    name = p.get("name")
    if name:
        projects[p.get("path") or name] = name

hits = []
for path, name in sorted(projects.items()):
    for d in DROP:
        d = d.rstrip("/")
        if path == d or path.startswith(d + "/"):
            hits.append((path, name)); break

out = ['<?xml version="1.0" encoding="UTF-8"?>', "<manifest>",
       "  <!-- generated by gen-local-manifest.sh — see BUILDING.md -->"]
out += [f'  <remove-project name="{n}" />   <!-- {p} -->' for p, n in hits]
present = set(projects)
readd = [(p, n) for p, n in ADD_BACK.items() if p not in present]
if readd:
    out.append("  <!-- providers TWRP removes that kept projects still depend on -->")
    out += [f'  <project path="{p}" name="{n}" />' for p, n in readd]
out.append("</manifest>")

tmp   = "/aosp/.repo/local_manifests/.warhol_removals.xml.tmp"
final = "/aosp/.repo/local_manifests/warhol_removals.xml"
open(tmp, "w").write("\n".join(out) + "\n")
os.replace(tmp, final)
print(f"local manifest: removing {len(hits)} of {len(projects)} projects; adding back {len(readd)}")
for p, _ in readd:
    print(f"    + {p}")
for p, _ in hits:
    print(f"    {p}")
PY
