#!/usr/bin/env bash
# =============================================================================
# gen-proprietary-files.sh — build a LineageOS-style proprietary-files.txt from
#                            extracted vendor/ and odm/ partitions.
#
#   ./tools/gen-proprietary-files.sh <extracted-vendor-dir> <extracted-odm-dir>
#
# Produces lineage/warhol/proprietary-files.txt, grouped by subsystem so it is
# reviewable rather than a 5000-line dump.
#
# NOTE ON STRATEGY: for a Treble device like warhol, extracting every blob is
# usually the WRONG approach. The stock vendor/odm/vendor_dlkm partitions already
# satisfy the 150 HALs the framework needs, and the device is
# `ro.treble.enabled=true` with vendor API level 202504. Building only
# system/product/system_ext against the stock vendor is far less work and far
# less fragile. This list is therefore primarily an INVENTORY — use it to know
# what exists and what each piece is for, not necessarily to copy all of it.
# =============================================================================
set -euo pipefail
V="${1:-}"; O="${2:-}"
[ -d "$V" ] && [ -d "$O" ] || { sed -n '3,10p' "$0" | sed 's/^# \{0,1\}//'; exit 1; }
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$ROOT/lineage/warhol/proprietary-files.txt"
mkdir -p "$(dirname "$OUT")"

FP="$(grep -m1 '^ro.vendor.build.fingerprint=' "$V/build.prop" 2>/dev/null | cut -d= -f2- || echo unknown)"

emit_group() {   # emit_group <title> <regex>
    local title="$1" re="$2" n=0
    {
        echo ""
        echo "## $title"
    } >> "$OUT"
    for base in vendor odm; do
        dir="$V"; [ "$base" = odm ] && dir="$O"
        while IFS= read -r f; do
            echo "$base/${f#$dir/}" >> "$OUT"; n=$((n+1))
        done < <(find "$dir" -type f 2>/dev/null | grep -iE "$re" | sort)
    done
    printf '  %-22s %s files\n' "$title" "$n"
}

{
  echo "# Proprietary files for warhol (Xiaomi 17T Pro, MT6993)"
  echo "#"
  echo "# Generated by tools/gen-proprietary-files.sh"
  echo "# All blobs from: $FP"
  echo "#"
  echo "# See the note in the generator: on this Treble device, reusing the stock"
  echo "# vendor/odm partitions is usually preferable to copying these out."
} > "$OUT"

emit_group "Camera"       '/(bin/hw/)?[^/]*camera|mialgo|camerahalserver|/etc/camera/'
emit_group "Fingerprint"  'fingerprint|goodix_fod|biometric'
emit_group "Radio / modem" '/(bin|lib64)/[^/]*(ril|radio|ccci|modem|imsa|mtk_agps)'
emit_group "IR blaster"   'consumerir|hardware\.ir-'
emit_group "Audio"        '/(bin/hw/|lib64/)[^/]*audio|dolby|speaker|aurisys|soundtrigger'
emit_group "Sensors"      '/(bin/hw/|lib64/)[^/]*sensor|citsensor|contexthub'
emit_group "NFC / SE"     'nfc|secure_element|omapi'
emit_group "Wi-Fi / BT"   'wifi|wlan|bluetooth|connsys|conninfra|wmt_|BT_'
emit_group "GPU / display" 'libGLES|mali|MEOW|gralloc|composer|displayfeature|hwcomposer'
emit_group "NPU / APU"    'apu|neuron|mdla|mvpu|aiste'
emit_group "Vibrator"     'vibrator|aw8697'
emit_group "Power/thermal" 'thermal|powerhal|perfservice|mtkpower'
emit_group "Firmware"     '/firmware/'

echo
echo "wrote $OUT ($(grep -vcE '^(#|$)' "$OUT") entries)"
